config/routes.rb
Rails.application.routes.draw do

  root 'messages#home'
  match '/all_mail',      to: 'messages#all_mails',    via: 'get'
  match '/sent_mail',     to: 'messages#sent_mails',   via: 'get'
  match '/inbox_mail',    to: 'messages#inbox_mails',  via: 'get'
  match '/show_message',  to: 'messages#show_message', via: 'get'


  resources :users, except: [:index]
  match '/all_users',     to: 'users#index',             via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',        to: 'sessions#new',            via: 'get'
  match '/signout',       to: 'sessions#destroy',        via: 'delete'


  resources :conversations, only: [:new, :create]
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user, foreign_key: :sender_id

  mount_uploader :attachment
  validates_presence_of :title, :body, :conversation_id, :sender_id

  scope :all_mails_model, -> (user) do
    includes(:user, :conversation)
    .joins(:conversation)
    .order(created_at: :desc)
    .where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :sent_mails_model, -> (user) do
    includes(:user)
    .where(sender_id: user)
    .joins(:conversation)
    .order(created_at: :desc)
    .where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :inbox_mails_model, -> (user) do
    includes(:user)
    .where.not(sender_id: user)
    .joins(:conversation)
    .order(created_at: :desc)
    .where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :show_message_model, -> (message) do
    includes(:conversation)
    .select('messages.title, messages.body, messages.created_at, messages.attachment, messages.conversation_id')
    .joins(:conversation)
    .find_by_id(message)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user

  def home
  end

  def all_mails
    @messages = Message.all_mails_model(current_user)
  end

  def sent_mails
    @messages = Message.sent_mails_model(current_user)
    render "all_mails"
  end

  def inbox_mails
    @messages = Message.inbox_mails_model(current_user)
    render "all_mails"
  end

  def show_message
    @message = Message.show_message_model(params[:message_id])
  end

end

app/views/messages/_messages.html.haml
- messages.each do |message|
  %tr
    %td= link_to "#{message.user.name}", show_message_path(message_id: message)
    %td= message.title
    %td= time_ago_in_words(message.created_at)

app/views/messages/all_mails.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= "Sender message"
      %th= "Title message"
      %th= "Create message"
  %tbody
    = render partial: "messages", object: @messages

app/views/messages/home.html.erb
<h1>Please login or register</h1>

app/views/messages/show_message.html.haml
- if @message.user == current_user
  %h1= "Sent to the #{ User.find_by_id(@message.conversation.recipient_id).name }"
- else
  %h1= "Obtained from the #{ @message.user.name }"
= @message.title
%h5= @message.body
%h5= time_ago_in_words(@message.created_at)
= link_to "Download file", @message.attachment_url