config/routes.rb
Rails.application.routes.draw do

  root 'messages#home'
  match '/all_mail',      to: 'messages#all_mails',    via: 'get'
  match '/sent_mail',     to: 'messages#sent_mails',   via: 'get'
  match '/inbox_mail',    to: 'messages#inbox_mails',  via: 'get'
  match '/show_message',  to: 'messages#show_message', via: 'get'


  resources :users, except: [:index]
  match '/all_users',     to: 'users#index',             via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',        to: 'sessions#new',            via: 'get'
  match '/signout',       to: 'sessions#destroy',        via: 'delete'


  resources :conversations, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  before_create :the_first_user_is_admin
  #################validates####################
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  ##################association#################
  has_many :conversations, foreign_key: :sender_id
  has_many :messages

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

    def the_first_user_is_admin
      if User.count == 0
        self.admin = true
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [ :edit, :update, :show ]
  before_action :correct_user,   only: [ :edit, :update ]
  before_action :admin_user,     only: [ :destroy ]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Registration Succesful"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your profile updated successful"
      redirect_to @user
    else
      flash[:error] = "Eroors"
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id]).destroy
    flash[:success] = "User #{user.name} deleted."
    redirect_to all_users_path
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    def admin_user
      redirect_to(root_url) if !current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :name, required: false
  = f.input :email, required: false
  = f.input :password
  = f.input :password_confirmation, label: "Confirmation"
  = f.submit "Submit", class: "btn btn-large btn-primary"

app/views/users/_index.html.haml
- @users.each_with_index  do |user,index|
  -if !current_user?(user)
    %tr
      %td= link_to "#{user.name}", user
      %td= link_to "#{user.email}", user
      - if current_user.admin?
        %td= link_to "Delete user only for admin", user, class: "btn-group btn btn-danger", method: :delete, data: { confirm: "You sure?" }

app/views/users/_user.html.haml
%li
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    = link_to "Delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.haml
%h4 Update your profile
= render 'form'

app/views/users/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= "Name users"
      %th= "Email users"
      - if current_user.admin?
        %th= "Links to delete"
  %tbody
    = render "index"
= will_paginate

app/views/users/new.html.haml
%h4 The page registration
= render 'form'

app/views/users/show.html.haml
.row
  %aside.span4
    %section
      %h1= @user.name
      %h2= @user.email
      -if current_user.admin?
        = link_to "edit user to admin", edit_user_path(@user), class: "btn-group btn btn-danger"
      - if !current_user?(@user)
        %h2 Write a message:
        = simple_form_for :conversation, { url: conversations_path } do |f|
          = f.hidden_field :recipient_id, value: @user.id
          = f.hidden_field :user_to_flash, value: @user.name
          = f.input :title, as: :string, label: false, placeholder: "Title", required: false
          = f.input :body, as: :text, label: false, placeholder: "Text", required: false
          = f.submit "Submit"