config/routes.rb
Rails.application.routes.draw do

  root 'messages#home'
  match '/all_mail',      to: 'messages#all_mails',    via: 'get'
  match '/sent_mail',     to: 'messages#sent_mails',   via: 'get'
  match '/inbox_mail',    to: 'messages#inbox_mails',  via: 'get'
  match '/show_message',  to: 'messages#show_message', via: 'get'


  resources :users, except: [:index]
  match '/all_users',     to: 'users#index',             via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',        to: 'sessions#new',            via: 'get'
  match '/signout',       to: 'sessions#destroy',        via: 'delete'


  resources :conversations, only: [:new, :create]
end

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_flash_class(type)} fade in" }
    = message
    %button.close{ data: { dismiss: 'alert' } } x

app/views/layouts/_header.html.haml
.nav.navbar.navbar-default
  .container
    .navbar-brand
      %li= link_to "Home page", root_path
    %ul.nav.navbar-nav
      - if signed_in?
        %li= link_to "All users", all_users_path
        %li= link_to "My profile", current_user
        %li= link_to "Settings profile", edit_user_path(current_user)
        %li= link_to "Sign out", signout_path, method: "delete"
      - else
        %li= link_to "Sign in", signin_path
        %li= link_to "Registration", new_user_path

app/views/layouts/_left_sidebar.html.haml
%li= link_to "Compose", new_conversation_path
%li= link_to "All mail", all_mail_path
%li= link_to "Inbox", inbox_mail_path
%li= link_to "Sent Mail", sent_mail_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Project2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/header'
      = render 'layouts/flash'
      - if signed_in?
        .container-fluid
          .row-fluid
            .col-sm-4.col-md-3
              .nav.nav-sidebar
                = render 'layouts/left_sidebar'
            .col-sm-8.col-md-9
              .row.placeholders
                = yield
      - else
        = yield